# Generated by Django 4.1.7 on 2023-04-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='L_impact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=50, null=True)),
                ('numero_tel', models.CharField(max_length=50, null=True)),
                ('participant', models.CharField(max_length=250, null=True)),
                ('a_participe', models.BooleanField(default=True)),
                ('qr_code_data', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
