# Generated by Django 4.1.7 on 2023-04-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinolu_event_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='l_impact',
            name='date_inscription',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='l_impact',
            name='a_participe',
            field=models.BooleanField(default=False),
        ),
    ]
